import { Strategy, StrategyStatusEnum } from "@/types/strategy.type";
import {
  OrderStatusEnum,
  OrderTypeEnum,
  PriceTypeEnum,
} from "@/types/token-order.type";

export const strategiesData: Array<Strategy> = [
  {
    id: "1",
    title: "Popouw",
    status: StrategyStatusEnum.ACTIVE,
    createdAt: new Date().toDateString(),
    orderTokens: [
      {
        network: "Seven Metrics Coin",
        name1: "Ethereum",
        code1: "ETH",
        name2: "Solana",
        code2: "SOL",
        status: OrderStatusEnum.ACTIVE,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Bitcoin",
        code1: "BTC",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.EXECUTED,
        extraTokens: [
          {
            code: "SOL",
            name: "Solana",
          },
        ],
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Solana",
        code1: "SOL",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.CANCELLED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
    ],
  },
  {
    id: "2",
    title: "Popouw",
    status: StrategyStatusEnum.ACTIVE,
    createdAt: new Date().toDateString(),
    orderTokens: [
      {
        network: "Seven Metrics Coin",
        name1: "Ethereum",
        code1: "ETH",
        name2: "Solana",
        code2: "SOL",
        status: OrderStatusEnum.ACTIVE,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Bitcoin",
        code1: "BTC",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.EXECUTED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Solana",
        code1: "SOL",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.CANCELLED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
    ],
  },
  {
    id: "3",
    title: "Popouw",
    status: StrategyStatusEnum.ACTIVE,
    createdAt: new Date().toDateString(),
    orderTokens: [
      {
        network: "Seven Metrics Coin",
        name1: "Ethereum",
        code1: "ETH",
        name2: "Solana",
        code2: "SOL",
        status: OrderStatusEnum.ACTIVE,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Bitcoin",
        code1: "BTC",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.EXECUTED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Solana",
        code1: "SOL",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.CANCELLED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
    ],
  },
  {
    id: "4",
    title: "Popouw",
    status: StrategyStatusEnum.ACTIVE,
    createdAt: new Date().toDateString(),
    orderTokens: [
      {
        network: "Seven Metrics Coin",
        name1: "Ethereum",
        code1: "ETH",
        name2: "Solana",
        code2: "SOL",
        status: OrderStatusEnum.ACTIVE,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Bitcoin",
        code1: "BTC",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.EXECUTED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Solana",
        code1: "SOL",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.CANCELLED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
    ],
  },
  {
    id: "5",
    title: "Popouw",
    status: StrategyStatusEnum.ACTIVE,
    createdAt: new Date().toDateString(),
    orderTokens: [
      {
        network: "Seven Metrics Coin",
        name1: "Ethereum",
        code1: "ETH",
        name2: "Solana",
        code2: "SOL",
        status: OrderStatusEnum.ACTIVE,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Bitcoin",
        code1: "BTC",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.EXECUTED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Solana",
        code1: "SOL",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.CANCELLED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
    ],
  },
  {
    id: "6",
    title: "Popouw",
    status: StrategyStatusEnum.ACTIVE,
    createdAt: new Date().toDateString(),
    orderTokens: [
      {
        network: "Seven Metrics Coin",
        name1: "Ethereum",
        code1: "ETH",
        name2: "Solana",
        code2: "SOL",
        status: OrderStatusEnum.ACTIVE,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Bitcoin",
        code1: "BTC",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.EXECUTED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Solana",
        code1: "SOL",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.CANCELLED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
    ],
  },
  {
    id: "7",
    title: "Popouw",
    status: StrategyStatusEnum.ACTIVE,
    createdAt: new Date().toDateString(),
    orderTokens: [
      {
        network: "Seven Metrics Coin",
        name1: "Ethereum",
        code1: "ETH",
        name2: "Solana",
        code2: "SOL",
        status: OrderStatusEnum.ACTIVE,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Bitcoin",
        code1: "BTC",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.EXECUTED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Solana",
        code1: "SOL",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.CANCELLED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
    ],
  },
  {
    id: "8",
    title: "Popouw",
    status: StrategyStatusEnum.ACTIVE,
    createdAt: new Date().toDateString(),
    orderTokens: [
      {
        network: "Seven Metrics Coin",
        name1: "Ethereum",
        code1: "ETH",
        name2: "Solana",
        code2: "SOL",
        status: OrderStatusEnum.ACTIVE,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Bitcoin",
        code1: "BTC",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.EXECUTED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Solana",
        code1: "SOL",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.CANCELLED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
    ],
  },
  {
    id: "9",
    title: "Popouw",
    status: StrategyStatusEnum.ACTIVE,
    createdAt: new Date().toDateString(),
    orderTokens: [
      {
        network: "Seven Metrics Coin",
        name1: "Ethereum",
        code1: "ETH",
        name2: "Solana",
        code2: "SOL",
        status: OrderStatusEnum.ACTIVE,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Bitcoin",
        code1: "BTC",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.EXECUTED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Solana",
        code1: "SOL",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.CANCELLED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
    ],
  },
  {
    id: "10",
    title: "Popouw",
    status: StrategyStatusEnum.ACTIVE,
    createdAt: new Date().toDateString(),
    orderTokens: [
      {
        network: "Seven Metrics Coin",
        name1: "Ethereum",
        code1: "ETH",
        name2: "Solana",
        code2: "SOL",
        status: OrderStatusEnum.ACTIVE,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Bitcoin",
        code1: "BTC",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.EXECUTED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
      {
        network: "Seven Metrics Coin",
        name1: "Solana",
        code1: "SOL",
        name2: "Ethereum",
        code2: "ETH",
        status: OrderStatusEnum.CANCELLED,
        orders: [
          {
            id: 3,
            budget: 2000,
            order_type: OrderTypeEnum.BUY,
            price_type: PriceTypeEnum.SINGLE,
            price: 3214,
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
          {
            id: 4,
            budget: 2000,
            order_type: OrderTypeEnum.SELL,
            price_type: PriceTypeEnum.RANGE,
            prices: [5347.94, 3214, 9873.43],
            status: OrderStatusEnum.ACTIVE,
            baseTokenShortName: "Test",
            baseTokenLongName: "Test",
            pairTokenShortName: "Test",
            pairTokenLongName: "Test",
            is_continuous: false,
          },
        ],
      },
    ],
  },
];
